# Generated by Django 4.2.5 on 2023-09-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('sub_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('sub_code', models.CharField(max_length=255)),
                ('sub_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='years',
            fields=[
                ('years_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('years', models.PositiveIntegerField()),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastpapers.subjects')),
            ],
            options={
                'db_table': 'Years',
            },
        ),
        migrations.CreateModel(
            name='papers',
            fields=[
                ('paper_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('is_mid_i', models.BooleanField(blank=True)),
                ('is_mid_ii', models.BooleanField(blank=True)),
                ('is_finals', models.BooleanField(blank=True)),
                ('is_lab_mid', models.BooleanField(blank=True)),
                ('is_lab_finals', models.BooleanField(blank=True)),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastpapers.years')),
            ],
            options={
                'db_table': 'Papers',
            },
        ),
    ]
